# site settings
author: Applied Blockchain
title: Applied Blockchain
description: "Building Future-Proof, Decentralised Solutions"

# social links
github: https://github.com/appliedblockchain/
linkedin: https://www.linkedin.com/company/applied-blockchain/
medium: 
twitter: https://twitter.com/appblockchain

# permalinks config
# projects
collections:
  projects:
    output: true
    permalink: /project/:path/
# posts
collections:
  posts:
    output: true
    permalink: /:title/

# internal path
resourceurl: /resources
imageurl: /resources/images