# site settings
author: Applied Blockchain
title: Applied Blockchain
description: "Building Future-Proof, Decentralised Solutions"

# social links
github: https://github.com/appliedblockchain/
linkedin: https://www.linkedin.com/company/applied-blockchain/
medium: https://medium.com/@AppBlockchain_
twitter: https://twitter.com/appblockchain

# permalinks config
collections:
  projects:
    output: true
    permalink: /projects/:path.html/
  posts:
    output: true
    permalink: /:title.html/

# internal path
resourceurl: /resources
imageurl: /resources/images