# site settings
author: Applied Blockchain
title: Applied Blockchain
description: "Building Future-Proof Blockchain Applications"

# contact 
address-london: Runway East<br>20 St Thomas St<br>London, SE1 9RG<br>United Kingdom
map-london: https://goo.gl/maps/2RqjmEGqHhP2
address-porto: District – Offices & Lifestyle<br>Rua Augusto Rosa 39<br>4000-098 Porto<br>Portugal
map-porto: https://goo.gl/maps/uomitvdoreF2

# social links
github: https://github.com/appliedblockchain/
linkedin: https://www.linkedin.com/company/applied-blockchain/
medium: https://medium.com/@AppBlockchain_
twitter: https://twitter.com/appblockchain

# permalinks config
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /:title/

# internal path
resourceurl: /resources
imageurl: /resources/images