# site settings
author: Applied Blockchain
title: Applied Blockchain
description: "Building Future-Proof, Decentralised Solutions"

# social links
twitter: https://twitter.com/appblockchain
github: https://github.com/appliedblockchain/

# projects config
collections:
  projects:
    output: true
    permalink: /projects/:path/

resourceurl: /resources
imageurl: /resources/images