# site settings
author: Applied Blockchain
title: Applied Blockchain
description: "Building Future-Proof, Decentralised Solutions"

# site settings
twitter: https://twitter.com/appblockchain
github: https://github.com/appliedblockchain/

# site settings
collections:
  projects:
    output: true
    permalink: /projects/:path/