# site settings
author: Applied Blockchain
title: Applied Blockchain
description: "Building Future-Proof Blockchain Applications"

# contact 
adress-london: Runway East<br>20 St Thomas St<br>London, SE1 9RG<br>United Kingdom
adress-porto: Rua de Cândido dos Reis<br>Porto<br>Portugal

# social links
github: https://github.com/appliedblockchain/
linkedin: https://www.linkedin.com/company/applied-blockchain/
medium: https://medium.com/@AppBlockchain_
twitter: https://twitter.com/appblockchain

# permalinks config
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /:title/

# internal path
resourceurl: /resources
imageurl: /resources/images