# site settings
author: Applied Blockchain
title: Applied Blockchain
description: "Building Future-Proof, Decentralised Solutions"

# social links
github: https://github.com/appliedblockchain/
linkedin: https://www.linkedin.com/company/applied-blockchain/
medium: 
twitter: https://twitter.com/appblockchain

# projects config
collections:
  projects:
    output: true
    permalink: /projects/:path/

resourceurl: /resources
imageurl: /resources/images