- title: "SILENTDATA"
  id: "silentdata" # DO NOT CHANGE !!
  logo: "silentdata"
  background: "silentdata.jpg"
  category: "Confidential Open Banking"
  status: "Live"
  description: "SILENTDATA is a confidential open banking platform that enables queries to be performed on individual and business bank accounts without revealing the banking data even to the platform host."
  links:
    - name: "Website"
      url: "https://silentdata.com/"
      icon: "fa fa-globe"
    - name: "App"
      url: "https://app.silentdata.com/"
      icon: "fa fa-desktop"

- title: "Beyond"
  id: "beyond" # DO NOT CHANGE !!
  logo: beyond-default-white
  background: "beyond.png"
  category: "Confidential Trading"
  status: "In development"
  description: "Beyond is a confidential trading platform where orders, volume and price data are not revealed even to the venue host."
  links:
    - name: "Website"
      url: "http://appliedblockchain.com/beyond"
      icon: "fab fa-github"

- title: "K<span class=\"body--zero\">0</span>"
  id: "k0" # DO NOT CHANGE !!
  logo: "k0"
  background: "k0.svg"
  category: "Zero Knowledge Proofs"
  status: "Experimental"
  description: "K<span class=\"body--zero\">0</span> (pronounced “K zero”) is a zero knowledge proof protocol that enables digital assets to be created, verified and traded privately and seamlessly across multiple enterprise blockchain platforms & networks."
  technos:
    - name: Ethereum
    - name: Hyperledger Fabric
  links:
    - name: "Technical description"
      url: "k0.pdf"
      type: "internal"
      icon: "fa fa-file-alt"
    - name: "Background paper"
      url: "k0-background.pdf"
      type: "internal"
      icon: "fa fa-file-alt"
    - name: "Github repo"
      url: "https://github.com/appliedblockchain/k0"
      icon: "fab fa-github"
